name: Build NMiner

on:
  push:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-22.04 }
          - { os: ubuntu-24.04 }
          - { os: windows-latest }

    steps:
      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake python3

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: |
          npm install --ignore-scripts

      - name: Build NMiner
        run: |
          mkdir -p build
          npm run build

      - name: Package NMiner (Linux)
        if: runner.os == 'Linux'
        run: |
          tar -czvf nminer-${{ matrix.config.os }}.tar.gz package.json index.js index.d.ts LICENSE build/Release/NMiner.node src/js/*.js

      - name: Package NMiner (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path "package.json", "index.js", "index.d.ts", "LICENSE", "build/Release/NMiner.node", "src/js/*.js" -DestinationPath "nminer-windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nminer-${{ matrix.config.os }}
          path: |
            nminer-*.tar.gz
            nminer-*.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Release:')
    
    needs: build
    steps:
      - name: Download Files
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.2.5
          name: NMiner v1.2.5
          draft: true
          prerelease: false
          files: |
            artifacts/nminer-ubuntu-22.04.tar.gz
            artifacts/nminer-ubuntu-24.04.tar.gz
            artifacts/nminer-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}